---
name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  generate_zip:
    name: Generate release zip
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Check manifest.json version
        id: check_version
        run: |
          # Extract the version from manifest.json
          manifest_version=$(grep -oP '(?<="version": ")[^"]*' custom_components/lierda_iot/manifest.json)
          echo "Manifest.json version: $manifest_version"

          # Extract the tag (e.g., v2.0.1)
          tag="${GITHUB_REF#refs/tags/}"
          echo "Tag: $tag"

          # Strip 'v' prefix for comparison if present
          version_to_check="${tag#v}"
          echo "Version to check: $version_to_check"

          # Check if the versions match
          if [ "$version_to_check" != "$manifest_version" ]; then
            echo "Error: Tag version ($version_to_check) does not match manifest.json version ($manifest_version)"
            exit 1
          fi

      - name: Zip release file
        run: |
          sudo apt-get update || exit 1
          sudo apt-get install zip || exit 1

          echo "Show runner information"
          hostname
          whoami
          pwd
          uname -a

          echo "Show custom_components directory"
          ls -alht custom_components/lierda_iot/ || exit 1

          echo "Show manifest.json for debug"
          cat custom_components/lierda_iot/manifest.json || exit 1

          dst_dir="${{ github.workspace }}/artifacts"
          sudo mkdir -p "$dst_dir" || exit 1
          sudo chown -R "$(id -u):$(id -g)" "$dst_dir" || exit 1
          sudo chmod -R 755 "$dst_dir" || exit 1

          cd custom_components/lierda_iot/ || exit 1
          zip -r ../lierda_iot.zip ./* || exit 1
          cp ../lierda_iot.zip "$dst_dir/" || exit 1

          echo "Show artifacts directory"
          ls -alht "$dst_dir" || exit 1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lierda_iot.zip
          path: ${{ github.workspace }}/artifacts

  upload_release:
    needs: generate_zip
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          name: lierda_iot.zip
          merge-multiple: true

      - name: Display Structure of Artifacts Files
        run: ls -R

      - name: Show Working Directory For Debug Purpose
        run: |
          echo "Show runner information"
          hostname
          whoami
          df -h
          pwd
          uname -a
          ls -alht
          ls -alht artifacts || exit 0
          echo "github.ref: ${{github.ref}}"

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/lierda_iot.zip
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
